[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "generate-playlist"
version = "0.1.0"
description = ""
authors = ["Steven de jong <sdejong@cloudsuite.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.14"
appdirs = "1.4.4"
asgiref = "3.2.10"
bcrypt = "4.3.0"
cachelib = "0.1.1"
certifi = "2025.8.3"
cffi = "1.14.3"
chardet = "3.0.4"
click = "7.1.2"
cryptography = "3.1.1"
distlib = "0.4.0"
Django = "3.1"
django-filter = "2.3.0"
djangorestframework = "3.15.1"
filelock = "3.0.12"
flask = "1.1.2"
flask-migrate = "4.1.0"
flask-script = "2.0.6"
flask-session = "0.4.1"
gunicorn = "23.0.0"
idna = "2.10"
itsdangerous = "1.1.0"
Jinja2 = "2.11.2"
Mako = "1.3.10"
markupsafe = "<2.1"
Pillow = "*"
python-dotenv = "*"
pytz = "2020.1"
requests = "2.32.4"
six = "1.15.0"
spotipy = "2.16.0"
sqlparse = "0.5.3"
stevedore = "5.3.0"
urllib3 = "2.2.3"
virtualenv = "20.8.1"
virtualenv-clone = "0.5.4"
virtualenvwrapper = "4.8.4"
Werkzeug = "2.1.2"
