[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "playlist-generator"
version = "0.1.0"
description = ""
authors = ["Steven de jong <sdejong@cloudsuite.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.14"
appdirs = "1.4.4"
asgiref = "3.2.10"
bcrypt = "3.2.0"
cachelib = "0.1.1"
certifi = "*"
cffi = "*"
chardet = "*"
click = "*"
cryptography = "*"
distlib = "*"
Django = "3.1"
django-filter = "2.3.0"
djangorestframework = "3.11.1"
filelock = "*"
flask = "1.1.2"
flask-migrate = "2.5.3"
flask-session = "0.3.2"
gunicorn = "20.0.4"
idna = "*"
itsdangerous = "*"
Jinja2 = "*"
Mako = "*"
markupsafe = "<2.1"
Pillow = "*"
python-dotenv = "*"
pytz = "*"
requests = "*"
six = "*"
spotipy = "*"
sqlparse = "*"
stevedore = "*"
urllib3 = "*"
virtualenv = "*"
virtualenv-clone = "*"
Werkzeug = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
