"""add generation history tracks

Revision ID: 162d836fb8ab
Revises: e65f91d609fd
Create Date: 2026-04-16 14:52:10.501471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162d836fb8ab'
down_revision: Union[str, Sequence[str], None] = 'e65f91d609fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_history_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=50), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_discovery', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generation_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_history_tracks')
    # ### end Alembic commands ###
