"""add track cache and play history

Revision ID: 298ada6f810a
Revises: 162d836fb8ab
Create Date: 2026-04-16 15:48:25.781212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298ada6f810a'
down_revision: Union[str, Sequence[str], None] = '162d836fb8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=50), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('album_image_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_track_id')
    )
    op.create_table('play_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=50), nullable=False),
    sa.Column('played_at', sa.String(length=30), nullable=False),
    sa.Column('actual_play_ms', sa.Integer(), nullable=True),
    sa.Column('play_percentage', sa.Float(), nullable=True),
    sa.Column('was_skipped', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_track_id', 'played_at', name='uq_play_history')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_history')
    op.drop_table('track_cache')
    # ### end Alembic commands ###
