"""initial schema

Revision ID: e65f91d609fd
Revises: 
Create Date: 2026-04-16 12:41:06.323407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65f91d609fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.Float(), nullable=False),
    sa.Column('token_scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_user_id')
    )
    op.create_table('base_playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(length=50), nullable=False),
    sa.Column('playlist_name', sa.String(length=500), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_playlist_id', name='uq_base_playlist_user')
    )
    op.create_table('base_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=50), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('album_image_url', sa.Text(), nullable=True),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_track_id', name='uq_base_track_user')
    )
    op.create_table('blacklist_playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(length=50), nullable=False),
    sa.Column('playlist_name', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_playlist_id', name='uq_blacklist_playlist_user')
    )
    op.create_table('blacklist_tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=50), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_track_id', name='uq_blacklist_track_user')
    )
    op.create_table('cover_image_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bg_color', sa.String(length=7), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('font_name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_cover_config_user_name')
    )
    op.create_table('generation_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_playlist_id', sa.String(length=50), nullable=False),
    sa.Column('target_playlist_name', sa.String(length=500), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('discovery_count', sa.Integer(), nullable=False),
    sa.Column('max_tracks_param', sa.Integer(), nullable=True),
    sa.Column('max_minutes_param', sa.Integer(), nullable=True),
    sa.Column('discovery_mode', sa.String(length=20), nullable=True),
    sa.Column('discovery_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_playlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(length=50), nullable=False),
    sa.Column('playlist_name', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_playlist_id', name='uq_target_playlist_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_playlists')
    op.drop_table('generation_history')
    op.drop_table('cover_image_configs')
    op.drop_table('blacklist_tracks')
    op.drop_table('blacklist_playlists')
    op.drop_table('base_tracks')
    op.drop_table('base_playlists')
    op.drop_table('users')
    # ### end Alembic commands ###
