"""make spotify id unique

Revision ID: 1b775b9d9ad0
Revises: bda6f9de0ff1
Create Date: 2020-10-05 18:15:26.861929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b775b9d9ad0'
down_revision = 'bda6f9de0ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist', ['spotify_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blacklist', type_='unique')
    # ### end Alembic commands ###
