"""Add id type

Revision ID: bda6f9de0ff1
Revises: cd3685ee085a
Create Date: 2020-10-05 17:28:05.137063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda6f9de0ff1'
down_revision = 'cd3685ee085a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('id_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist', 'id_type')
    # ### end Alembic commands ###
